//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KöfteciYusuf.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GirisKontrol", ReplyAction="http://tempuri.org/IService1/GirisKontrolResponse")]
        bool GirisKontrol(string KullanıcıAdı, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GirisKontrol", ReplyAction="http://tempuri.org/IService1/GirisKontrolResponse")]
        System.Threading.Tasks.Task<bool> GirisKontrolAsync(string KullanıcıAdı, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/üyeOl", ReplyAction="http://tempuri.org/IService1/üyeOlResponse")]
        bool üyeOl(string ad, string email, string password, string tellno, string Kapıno, string daireno, int ilindex, int ilçeindex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/üyeOl", ReplyAction="http://tempuri.org/IService1/üyeOlResponse")]
        System.Threading.Tasks.Task<bool> üyeOlAsync(string ad, string email, string password, string tellno, string Kapıno, string daireno, int ilindex, int ilçeindex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ÖdemeKontrol", ReplyAction="http://tempuri.org/IService1/ÖdemeKontrolResponse")]
        bool ÖdemeKontrol(string Kartno, string SonKullanmaTarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ÖdemeKontrol", ReplyAction="http://tempuri.org/IService1/ÖdemeKontrolResponse")]
        System.Threading.Tasks.Task<bool> ÖdemeKontrolAsync(string Kartno, string SonKullanmaTarihi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : KöfteciYusuf.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<KöfteciYusuf.ServiceReference1.IService1>, KöfteciYusuf.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GirisKontrol(string KullanıcıAdı, string sifre) {
            return base.Channel.GirisKontrol(KullanıcıAdı, sifre);
        }
        
        public System.Threading.Tasks.Task<bool> GirisKontrolAsync(string KullanıcıAdı, string sifre) {
            return base.Channel.GirisKontrolAsync(KullanıcıAdı, sifre);
        }
        
        public bool üyeOl(string ad, string email, string password, string tellno, string Kapıno, string daireno, int ilindex, int ilçeindex) {
            return base.Channel.üyeOl(ad, email, password, tellno, Kapıno, daireno, ilindex, ilçeindex);
        }
        
        public System.Threading.Tasks.Task<bool> üyeOlAsync(string ad, string email, string password, string tellno, string Kapıno, string daireno, int ilindex, int ilçeindex) {
            return base.Channel.üyeOlAsync(ad, email, password, tellno, Kapıno, daireno, ilindex, ilçeindex);
        }
        
        public bool ÖdemeKontrol(string Kartno, string SonKullanmaTarihi) {
            return base.Channel.ÖdemeKontrol(Kartno, SonKullanmaTarihi);
        }
        
        public System.Threading.Tasks.Task<bool> ÖdemeKontrolAsync(string Kartno, string SonKullanmaTarihi) {
            return base.Channel.ÖdemeKontrolAsync(Kartno, SonKullanmaTarihi);
        }
    }
}
